### PR TITLE
Try to fix Hexagon(RowEven/RowOdd/ColumnEven/ColumnOdd) collider bugs.

### PR DESCRIPTION
**Pull request by darkautism**
Fix Hexagon colider bugs

image
image

### CODE REVIEW

**Comment by darkautism** [comment]
Need this patch: https://github.com/mapeditor/rs-tiled/pull/313

**Comment by darkautism** [comment]
Do not fix #41 .
If you want to flip the Y axis, do it independently.

**Comment by darkautism** [comment]
Also fix IsoCoordSystem::Diamond
image
image

**Comment by adrien-bon** [comment]
Hi!

Thanks for the PR and the example to reproduce the issue.
Actually, it seems we have an issue with colliders from tiles for hex and iso maps.
We only tested colliders from objects, not from tiles.
Now I understand your issue.

Regarding your code:
- we may not have to depend upon `hexside_length`. Have a look to https://github.com/adrien-bon/bevy_ecs_tiled/blob/main/src/loader.rs#L864. I'm not good at math (and I did not check yours thoroughly) but if we can it would be nice to unify how we handle objects (previous link) and tiles so we only have one "math" function for both
- you only applied your fix for "finite" maps. I believe "infinite" maps are a bit broken but if you have time it would be nice if you could try to apply your fix for them too, it may actually improve things
- the `debug_render` is a nice addition but it should go in the debug plugin
- not sure what's going on with CI, I'll have a look when I have more time

**Comment by darkautism** [comment]
- I'm afraid not, these arithmetic are not even multiplied by the number of cells, RowOdd even uses object_x directly, this does not work
- I have no way to fix the infinite map, it will crash in the tilemap crate.
- Moved

**Comment by darkautism** [comment]
This patch fix the tile collider not object collider.
I think this is helpful: https://bevyengine.org/examples/animation/custom-skinned-mesh/

**Comment by adrien-bon** [comment]
> This patch fix the tile collider not object collider.

Yes I know what you want to fix here.
What I am saying is that when I add tile colliders to the existing examples in the repo your fix does not work.
For instance, in the 1st screenshot,tile colliders should be on the mountain. Not to their left.

> I think this is helpful: https://bevyengine.org/examples/animation/custom-skinned-mesh/

Not sure what do you mean ?

**Comment by darkautism** [comment]
According to #32, these object deformers not only have incorrect positions, they also need to be deformed.

**Comment by adrien-bon** [comment]
#32 is another issue that applies only to isometric maps, where colliders have the proper position (at least object colliders) but not the proper shape.

Here we are trying to fix tile colliders not having a correct position, both for hexagonal and isometric maps.
As I said, I think the maths you added does not fix the tile collider position issue. Please, have a look to the screenshot I posted (there is an issue with hexagonal maps too, not only isometric).

Indeed, if we achieve in this PR a status where tile colliders have the correct position but not the proper shape for isometric maps I'll consider it done and that the shape issue will be fixed in #32.

**Pull request closed without merging**
